### PR TITLE
fix one warning

### PR DESCRIPTION
**Pull request by ZJH9Rondo**
I learned some about coffeescript ' class ', this commit I just run in editor,it's right,so I think I should to update it,If you think this change is no useful, I want know the reason why, because I was so excited when I found the question, before this, I hadn't commit anyone to open source, so I was so nervous when I chat with you

### CODE REVIEW

**Comment by joscha** [comment]
Hi @ZJH9Rondo, I appreciate your effort to, contribute to open source, however, please have a look at https://stackoverflow.com/a/3034952/217357 - the extra brackets are unnecessary in this case.

**Comment by ZJH9Rondo** [comment]
Yeah, thank you tell me the reason why you think, but I also think we should  use '' Tesseract() " ,and the reason why  ' new Tesseract() ' should be preferred over ' new Tesseract ' is because of the precedence is different. I always use JsLint ,so I think if we write by this. our code would be better in use, although this won't be influence the code,but the most important reason why I add commit is that the package is not use by yourself, also have many people to download by npm,that's all. thank you.

**Comment by joscha** [comment]
I agree in terms of linting if the code was written in JavaScript, but for CoffeeScript it's a different case. Your linter should ignore anything in `node_modules` anyway. Sorry.

**Comment by ZJH9Rondo** [comment]
I just see some, I found what you write is right, I'm sorry for that,but I want know how can I improve my ability in Web, would you teach me?

**Comment by joscha** [comment]
Just do what you did and contribute to open source, it will improve your skill with every pull request you open :thumbsup:

**Pull request closed without merging**
