### PR TITLE
small change in nodecr

### PR DESCRIPTION
**Pull request by ZJH9Rondo**
I think the code would be better in use when I changed it,if you don't think so,what you write also need changed from " tesseract = new tesseract" to " tesseract = new tesseract() ",All of that just is myself thoughts,what do you think ? I'm waiting for your reply

### CODE REVIEW

**Comment by joscha** [comment]
I don't think it makes a difference for the usage of the library. Also, you only changed the lib, which is generated from the coffeescript source.

**Comment by ZJH9Rondo** [comment]
I know what's the mening of your said, but when I review the code in editor, I saw one warning ,just because what you did't write, and what I found is just a small question, if you admit to merge it,the last line shou be change from "module.exports = tesseract " to "module.exports = Tesseract"

**Comment by joscha** [comment]
`Tesseract` is the class, whereas `tesseract` is an instance of it. As there is no reasom to have more than one instance of `Tesseract` at a time, an instance is the default export of this module. If you need access to the class - for whatever reason - we can add a named export for it, however this change has to be done in the coffeescript source.

**Comment by ZJH9Rondo** [comment]
I'm sorry for that waste your time,but I know what should I do now, and I will change the coffeescript when I find where is , so please give me the chance,although it just a small question and won't influence the code.thanks

**Pull request closed without merging**
